image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - java -jar ./artifacts/app-replan-delivery.jar &
  - chmod +x gradlew
  - choco install googlechrome --g 122.0.6261.128 -y


build_script:
  - ./gradlew test --info -Dselenide.headless=true